import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ChangeThemeProvider from "@/components/providers/change-theme-provider";
import ChangeThemeHTML from "@/components/ChangeTheme";

const roboto = Roboto({ weight: ['100', '400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s - E.E.T 3117',
    default: 'Plataforma - E.E.T 3117'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ChangeThemeProvider>
      <ChangeThemeHTML>
        <body className={roboto.className}>{children}</body>
      </ChangeThemeHTML>
    </ChangeThemeProvider>
  );
}
