import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ weight: ['100', '400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s - E.E.T 3117',
    default: 'Plataforma - E.E.T 3117'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="light">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
